# Generated by Django 2.0.2 on 2018-02-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, unique=True)),
                ('console', models.CharField(max_length=50, unique=True)),
                ('releasedate', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=5000, unique=True)),
                ('fondmemories', models.CharField(max_length=10000, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
