# Generated by Django 2.0.2 on 2018-02-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gameslist_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameslist',
            name='model_pic',
        ),
    ]
