# Generated by Django 2.0.2 on 2018-02-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gameslist_model_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameslist',
            old_name='model_pic',
            new_name='game_pic',
        ),
    ]
