# Generated by Django 2.0.2 on 2018-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180228_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameslist',
            old_name='releasedate',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='gameslist',
            name='game_pic',
            field=models.ImageField(default='staticfiles/None/no-img.jpg', upload_to='staticfiles/'),
        ),
    ]
