# Generated by Django 2.0.2 on 2018-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180304_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='console',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gameslist',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='gameslist',
            name='fond_memories',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='gameslist',
            name='release_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gameslist',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
