# Generated by Django 2.0.2 on 2018-03-12 13:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180312_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='console',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Playstation'), ('item_key2', 'N64'), ('item_key3', 'Snes'), ('item_key4', 'Sega')], max_length=39),
        ),
    ]
