# Generated by Django 2.0.2 on 2018-03-12 13:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180312_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='console',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Playstation'), ('item_key2', 'Nes'), ('item_key3', 'N64'), ('item_key4', 'Snes/Famicom (multi region release)'), ('item_key5', 'Snes(PAL release only)'), ('item_key6', 'Famicim(North America release only)'), ('item_key7', 'Snes(PAL release only)'), ('item_key8', 'Sega')], max_length=79),
        ),
    ]
