# Generated by Django 2.0.2 on 2018-03-12 15:56

from django.db import migrations
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180312_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslist',
            name='collector_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key9', 'Keeping'), ('item_key10', 'Trading'), ('item_key11', 'Selling')], default=django.utils.timezone.now, max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameslist',
            name='console',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Playstation'), ('item_key2', 'Nes'), ('item_key3', 'N64'), ('item_key4', 'Snes/Famicom (multi region release)'), ('item_key5', 'Snes(Europe release only)'), ('item_key6', 'Famicom(North America release only)'), ('item_key7', 'Famicom(Japan release only)'), ('item_key8', 'Gameboy'), ('item_key9', 'Gameboy Advanced'), ('item_key8', 'Sega mega-drive')], max_length=99),
        ),
    ]
