# Generated by Django 2.0.2 on 2018-03-12 15:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180312_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='collector_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Keeping'), ('item_key2', 'Trading'), ('item_key3', 'Selling')], max_length=29),
        ),
    ]
