# Generated by Django 2.0.2 on 2018-03-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180312_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameslist',
            name='collector_status',
        ),
    ]
