# Generated by Django 2.0.2 on 2018-03-12 17:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_gameslist_collector_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='console',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Playststion', 'Playstation'), ('Nes', 'Nes'), ('N64', 'N64'), ('Snes/Famicom (multi region release)', 'Snes/Famicom (multi region release)'), ('Snes(Europe release only)', 'Snes(Europe release only)'), ('Famicom(North America release only)', 'Famicom(North America release only)'), ('Famicom(Japan release only)', 'Famicom(Japan release only)'), ('Gameboy', 'Gameboy'), ('Gameboy Advanced', 'Gameboy Advanced'), ('Sega mega-drive', 'Sega mega-drive')], max_length=186),
        ),
    ]
