# Generated by Django 2.0.2 on 2018-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180315_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslist',
            name='user_rating',
            field=models.CharField(default=5, max_length=225),
            preserve_default=False,
        ),
    ]
