# Generated by Django 2.0.2 on 2018-03-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_gameslist_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameslist',
            name='release_date',
        ),
    ]
