# Generated by Django 2.0.2 on 2018-03-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_gameslist_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameslist',
            name='release_date',
        ),
    ]
