# Generated by Django 2.0.2 on 2018-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_gameslist_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='release_date',
            field=models.CharField(max_length=10),
        ),
    ]
