# Generated by Django 2.0.2 on 2018-03-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_gameslist_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameslist',
            name='user_rating',
        ),
    ]
