# Generated by Django 2.0.2 on 2018-03-15 19:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_gameslist_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslist',
            name='user_rating',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5'), ('7.0', '7.0'), ('7.5', '7.5'), ('8.0', '8.0'), ('8.5', '8.5'), ('9.0', '9.0'), ('9.5', '9.5'), ('10', '10')], default=1.0, max_length=78),
            preserve_default=False,
        ),
    ]
