# Generated by Django 2.0.2 on 2018-03-23 00:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_gameslist_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='console',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Playststion', 'Playstation'), ('PC', 'PC'), ('Commodore 64', 'Commodore 64'), ('Nes', 'Nes'), ('N64', 'N64'), ('Snes/Famicom (multi region release)', 'Snes/Famicom (multi region release)'), ('Snes(Europe release only)', 'Snes(Europe release only)'), ('Famicom(North America release only)', 'Famicom(North America release only)'), ('Famicom(Japan release only)', 'Famicom(Japan release only)'), ('Gameboy', 'Gameboy'), ('Gameboy Advanced', 'Gameboy Advanced'), ('Nintendo Gamecube', 'Nintendo Gamecube'), ('Sega Master System', 'Sega Master System'), ('Sega Mega-Drive/Genesis', 'Sega Mega-Drive/Genesis'), ('Sega Saturn', 'Sega Saturn'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Sega Gamegear', 'Sega Gamegear'), ('Sony Playstation', 'Sony Playstation'), ('Sony Playstation 2', 'Sony Playstation 2'), ('Microsoft Xbox', 'Microsoft Xbox')], max_length=339),
        ),
        migrations.AlterField(
            model_name='gameslist',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
