# Generated by Django 2.0.2 on 2018-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180323_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='game_pic',
            field=models.ImageField(default='staticfiles/None/no-img.jpg', upload_to='game_image'),
        ),
    ]
