# Generated by Django 2.0.2 on 2018-04-06 18:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180328_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='console',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Playstation', 'Playstation'), ('PC', 'PC'), ('Commodore 64', 'Commodore 64'), ('Nes', 'Nes'), ('N64', 'N64'), ('Snes/Famicom (multi region release)', 'Snes/Famicom (multi region release)'), ('Snes(Europe release only)', 'Snes(Europe release only)'), ('Famicom(North America release only)', 'Famicom(North America release only)'), ('Famicom(Japan release only)', 'Famicom(Japan release only)'), ('Gameboy', 'Gameboy'), ('Gameboy Advanced', 'Gameboy Advanced'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Nintendo Gamecube', 'Nintendo Gamecube'), ('Nintendo Wii', 'Nintendo Wii'), ('Nintendo WiiU', 'Nintendo WiiU'), ('Nintendo Switch', 'Nintendo Switch'), ('Sega Master System', 'Sega Master System'), ('Sega Mega-Drive/Genesis', 'Sega Mega-Drive/Genesis'), ('Sega Saturn', 'Sega Saturn'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Sega Gamegear', 'Sega Gamegear'), ('Sony Playstation', 'Sony Playstation'), ('Sony Playstation 2', 'Sony Playstation 2'), ('Sony Playstation 3', 'Sony Playstation 3'), ('Sony Playstation 4', 'Sony Playstation 4'), ('Microsoft Xbox', 'Microsoft Xbox'), ('Microsoft Xbox360', 'Microsoft Xbox360'), ('Microsoft XboxONE', 'Microsoft XboxONE')], max_length=481),
        ),
    ]
