# Generated by Django 2.0.2 on 2018-04-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180414_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleslist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articleslist',
            name='fond_memories',
        ),
        migrations.RemoveField(
            model_name='articleslist',
            name='game_pic',
        ),
        migrations.RemoveField(
            model_name='articleslist',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='articleslist',
            name='user_rating',
        ),
    ]
