# Generated by Django 2.0.2 on 2018-04-14 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0035_auto_20180414_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articleslist',
            new_name='Articlelist',
        ),
    ]
