# Generated by Django 2.0.2 on 2018-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_articleslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleslist',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
