# Generated by Django 2.0.2 on 2018-05-08 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180426_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslist',
            name='score',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newslist', to=settings.AUTH_USER_MODEL),
        ),
    ]
