# Generated by Django 2.0.2 on 2018-05-08 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20180508_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='score',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
