# Generated by Django 2.0.2 on 2018-05-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20180508_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameslist',
            name='user_rating',
        ),
    ]
