# Generated by Django 2.0.2 on 2018-05-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20180509_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleslist',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='articleslist',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='articleslist',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='articleslist',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='newslist',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='newslist',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='newslist',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='newslist',
            name='content4',
        ),
    ]
