# Generated by Django 2.0.2 on 2018-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180509_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleslist',
            name='content1',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='articleslist',
            name='content2',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='articleslist',
            name='content3',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='articleslist',
            name='content4',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='newslist',
            name='content1',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='newslist',
            name='content2',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='newslist',
            name='content3',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='newslist',
            name='content4',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
