# Generated by Django 2.0.2 on 2018-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20180509_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='content1',
            field=models.CharField(default='hgjg', max_length=10000),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='content2',
            field=models.CharField(default='hj', max_length=10000),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='content3',
            field=models.CharField(default='ghjghj', max_length=10000),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='content4',
            field=models.CharField(default='hjg', max_length=10000),
        ),
    ]
