# Generated by Django 2.0.2 on 2018-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20180509_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleslist',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
