# Generated by Django 2.0.2 on 2018-05-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_articleslist_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleslist',
            name='approved_comment',
        ),
    ]
